// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7kcwGOfs-HvwrgpsU8yWIx6bCO8l9lQ',
    appId: '1:1033855354360:android:5a3c9e18d822e46b19020d',
    messagingSenderId: '1033855354360',
    projectId: 'smart-market-list-82bf7',
    storageBucket: 'smart-market-list-82bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5-eXUl97Bw35t0sL8Leu7kzucVQoLD4M',
    appId: '1:1033855354360:ios:1882cb2a7ca666c119020d',
    messagingSenderId: '1033855354360',
    projectId: 'smart-market-list-82bf7',
    storageBucket: 'smart-market-list-82bf7.firebasestorage.app',
    iosClientId: '1033855354360-pfp6stmktqu0n9m7opdi56mg666dgtle.apps.googleusercontent.com',
    iosBundleId: 'com.brunoabreu.smartMarketList',
  );
}
