import 'package:intl/date_symbol_data_local.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'core/theme/app_theme.dart';
import 'data/models/shopping_item.dart';
import 'data/models/shopping_list.dart';
import 'data/models/shopping_note.dart';
import 'data/models/recipe.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:smart_market_list/l10n/generated/app_localizations.dart';
import 'providers/locale_provider.dart';
import 'providers/theme_provider.dart';
import 'ui/screens/main_screen.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Will be generated by user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print('⚠️ Firebase initialization failed: $e');
    print('If this is a new installation, please rebuild the app (Stop -> Run).');
  }

  await Hive.initFlutter();
  await initializeDateFormatting('pt_BR', null);
  
  Hive.registerAdapter(ShoppingItemAdapter());
  Hive.registerAdapter(ShoppingListAdapter());
  Hive.registerAdapter(ShoppingNoteAdapter());
  Hive.registerAdapter(RecipeAdapter());

  final box = await Hive.openBox<ShoppingList>('shopping_lists');
  await Hive.openBox<ShoppingNote>('shopping_notes');
  await Hive.openBox<Recipe>('recipes');
  await Hive.openBox<List<String>>('categories');
  await Hive.openBox<String>('hidden_suggestions');
  await Hive.openBox<ShoppingItem>('item_history');
  await Hive.openBox<double>('expense_goals');
  await Hive.openBox<List<String>>('list_shared_users');
  await Hive.openBox('settings'); // Open settings box
  
  // Migration: Ensure all lists use ID as key
  final keys = box.keys.toList();
  for (var key in keys) {
    if (key is int) {
      final list = box.get(key);
      if (list != null) {
        await box.delete(key);
        await box.put(list.id, list);
      }
    }
  }

  final settingsBox = Hive.box('settings');

  if (box.isEmpty) {
    final defaultList = ShoppingList(name: 'Compras do Mês', emoji: '🛒', budget: 500.0);
    await box.put(defaultList.id, defaultList);
    await settingsBox.put('default_list_id', defaultList.id);
  } else {
    // Migration: If default_list_id is missing, try to find "Compras do Mês"
    if (settingsBox.get('default_list_id') == null) {
      try {
        final defaultList = box.values.firstWhere((l) => l.name == 'Compras do Mês');
        await settingsBox.put('default_list_id', defaultList.id);
      } catch (_) {
        // No default list found, maybe user renamed/deleted it. Do nothing.
      }
    }
  }

  // Migration: Populate item_history from existing lists
  final historyBox = Hive.box<ShoppingItem>('item_history');
  if (historyBox.isEmpty) {
    for (final list in box.values) {
      for (final item in list.items) {
        final key = item.name.trim().toLowerCase();
        if (!historyBox.containsKey(key)) {
          await historyBox.put(key, item);
        }
      }
    }
  }

  runApp(const ProviderScope(child: SmartMarketListApp()));
}

class SmartMarketListApp extends ConsumerWidget {
  const SmartMarketListApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeModeProvider);
    final locale = ref.watch(localeProvider);

    return MaterialApp(
      title: 'Smart Market List',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      locale: locale,
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'), // English
        Locale('pt'), // Portuguese
      ],
      home: const MainScreen(),
    );
  }
}
